apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-worker-25705
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-worker-25705
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
